; Paradox Clock (PXC)
; Copyright (c) Paradox Productions 2018-2025
; IMPORTANT: Changes to this file require rebuilding the optimized page (npm run build)
; The built browser app reads values baked at build-time from this file.

[mqtt]
host = localhost
port = 1884
topic = paradox/houdini/clock
reconnect_interval = 5000
keep_alive = 60

[display]
fade_duration_default = 2
hint_duration_default = 15
clock_orientation = -90
seconds_tick_style = off  ; options: alternate | tick1 | tick2 | off

enable_console_logging = true
